---
# Backup current Dock configuration before modification
- name: Export current Dock configuration
  shell: |
    # Create a backup of the current dock layout
    dockutil --list > "{{ backup_dir.path | default(user_home + '/.config-backups/ansible-mac-' + ansible_date_time.epoch) }}/dock-layout-backup.txt" 2>/dev/null || echo "No existing dock items found"
  ignore_errors: yes

- name: Install dockutil for dock management
  homebrew:
    name: dockutil
    state: present
  tags: [dock]

- name: Clear existing Dock items
  shell: dockutil --remove all --no-restart
  ignore_errors: yes
  tags: [dock]

- name: Add applications to Dock (only if they exist)
  shell: |
    if [ -d "{{ item.path }}" ]; then
      dockutil --add "{{ item.path }}" --no-restart
    else
      echo "Skipping {{ item.name }} - not found at {{ item.path }}"
    fi
  loop:
    # System & Launcher
    - { name: "System Settings", path: "/System/Applications/System Settings.app" }
    - { name: "Launchpad", path: "/System/Applications/Launchpad.app" }
    
    # Communication & Meetings
    - { name: "Messages", path: "/System/Applications/Messages.app" }
    - { name: "WhatsApp", path: "/Applications/WhatsApp.app" }
    - { name: "Slack", path: "/Applications/Slack.app" }
    - { name: "Zoom", path: "/Applications/zoom.us.app" }
    
    # Terminals
    - { name: "iTerm", path: "/Applications/iTerm.app" }
    - { name: "Ghostty", path: "/Applications/Ghostty.app" }
    
    # Code Editors
    - { name: "Visual Studio Code", path: "/Applications/Visual Studio Code.app" }
    - { name: "Cursor", path: "/Applications/Cursor.app" }
    
    # Development Tools
    - { name: "Docker Desktop", path: "/Applications/Docker.app" }
    - { name: "TablePlus", path: "/Applications/TablePlus.app" }
    
    # Project Management
    - { name: "Linear", path: "/Applications/Linear.app" }
    - { name: "1Password", path: "/Applications/1Password.app" }
    
    # AI Assistants
    - { name: "ChatGPT", path: "/Applications/ChatGPT.app" }
    - { name: "Claude", path: "/Applications/Claude.app" }
    
    # Design & Content Creation
    - { name: "Figma", path: "/Applications/Figma.app" }
    - { name: "Screen Studio", path: "/Applications/Screen Studio.app" }
    - { name: "Obsidian", path: "/Applications/Obsidian.app" }
    
    # Browsers
    - { name: "Firefox", path: "/Applications/Firefox.app" }
    - { name: "Google Chrome", path: "/Applications/Google Chrome.app" }
    
    # Media & Utilities
    - { name: "Podcasts", path: "/System/Applications/Podcasts.app" }
    - { name: "Spotify", path: "/Applications/Spotify.app" }
  ignore_errors: yes
  tags: [dock]

- name: Add Downloads folder to Dock
  shell: dockutil --add "{{ user_home }}/Downloads" --view list --display folder --no-restart
  ignore_errors: yes
  tags: [dock]

- name: Restart Dock to apply changes
  shell: killall Dock
  tags: [dock]