---
- name: Clear existing Dock items
  osx_defaults:
    domain: com.apple.dock
    key: persistent-apps
    type: array
    value: []

- name: Add applications to Dock
  shell: |
    defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>{{ item.path }}</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
  loop:
    - { name: "System Settings", path: "file:///System/Applications/System%20Settings.app/" }
    - { name: "Launchpad", path: "file:///System/Applications/Launchpad.app/" }
    - { name: "WhatsApp", path: "file:///Applications/WhatsApp.app/" }
    - { name: "Messages", path: "file:///System/Applications/Messages.app/" }
    - { name: "Slack", path: "file:///Applications/Slack.app/" }
    - { name: "Zoom", path: "file:///Applications/zoom.us.app/" }
    - { name: "iTerm", path: "file:///Applications/iTerm.app/" }
    - { name: "Ghostty", path: "file:///Applications/Ghostty.app/" }
    - { name: "1Password", path: "file:///Applications/1Password.app/" }
    - { name: "Obsidian", path: "file:///Applications/Obsidian.app/" }
    - { name: "Visual Studio Code", path: "file:///Applications/Visual%20Studio%20Code.app/" }
    - { name: "Cursor", path: "file:///Applications/Cursor.app/" }
    - { name: "Linear", path: "file:///Applications/Linear.app/" }
    - { name: "TablePlus", path: "file:///Applications/TablePlus.app/" }
    - { name: "ChatGPT", path: "file:///Applications/ChatGPT.app/" }
    - { name: "Docker Desktop", path: "file:///Applications/Docker.app/Contents/MacOS/Docker%20Desktop.app/" }
    - { name: "Figma", path: "file:///Applications/Figma.app/" }
    - { name: "Firefox", path: "file:///Applications/Firefox.app/" }
    - { name: "Google Chrome", path: "file:///Applications/Google%20Chrome.app/" }
    - { name: "Podcasts", path: "file:///System/Applications/Podcasts.app/" }
    - { name: "Screen Sharing", path: "file:///System/Applications/Utilities/Screen%20Sharing.app/" }
    - { name: "Google Drive", path: "file:///Applications/Google%20Drive.app/" }

- name: Restart Dock to apply changes
  shell: killall Dock