---
- name: Install dockutil for dock management
  homebrew:
    name: dockutil
    state: present
  tags: [dock]

- name: Clear existing Dock items
  shell: dockutil --remove all --no-restart
  ignore_errors: yes
  tags: [dock]

- name: Add applications to Dock (only if they exist)
  shell: |
    if [ -d "{{ item.path }}" ]; then
      dockutil --add "{{ item.path }}" --no-restart
    else
      echo "Skipping {{ item.name }} - not found at {{ item.path }}"
    fi
  loop:
    - { name: "System Settings", path: "/System/Applications/System Settings.app" }
    - { name: "Launchpad", path: "/System/Applications/Launchpad.app" }
    - { name: "WhatsApp", path: "/Applications/WhatsApp.app" }
    - { name: "Messages", path: "/System/Applications/Messages.app" }
    - { name: "Slack", path: "/Applications/Slack.app" }
    - { name: "Zoom", path: "/Applications/zoom.us.app" }
    - { name: "iTerm", path: "/Applications/iTerm.app" }
    - { name: "Ghostty", path: "/Applications/Ghostty.app" }
    - { name: "1Password", path: "/Applications/1Password.app" }
    - { name: "Obsidian", path: "/Applications/Obsidian.app" }
    - { name: "Visual Studio Code", path: "/Applications/Visual Studio Code.app" }
    - { name: "Cursor", path: "/Applications/Cursor.app" }
    - { name: "Linear", path: "/Applications/Linear.app" }
    - { name: "TablePlus", path: "/Applications/TablePlus.app" }
    - { name: "ChatGPT", path: "/Applications/ChatGPT.app" }
    - { name: "Docker Desktop", path: "/Applications/Docker.app" }
    - { name: "Figma", path: "/Applications/Figma.app" }
    - { name: "Screen Studio", path: "/Applications/Screen Studio.app" }
    - { name: "Firefox", path: "/Applications/Firefox.app" }
    - { name: "Google Chrome", path: "/Applications/Google Chrome.app" }
    - { name: "Podcasts", path: "/System/Applications/Podcasts.app" }
    - { name: "Screen Sharing", path: "/System/Applications/Utilities/Screen Sharing.app" }
    - { name: "Google Drive", path: "/Applications/Google Drive.app" }
  ignore_errors: yes
  tags: [dock]

- name: Restart Dock to apply changes
  shell: killall Dock
  tags: [dock]