---
- name: Install MesloLGS Nerd Font
  get_url:
    url: "{{ item }}"
    dest: "{{ user_home }}/Library/Fonts/"
    mode: '0644'
  loop:
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
  ignore_errors: yes

- name: Create iTerm2 preferences directory
  file:
    path: "{{ user_home }}/Library/Preferences"
    state: directory

- name: Configure iTerm2 preferences
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop:
    # Font settings
    - { key: "Normal Font", type: "string", value: "MesloLGS-NF-Regular 13" }
    - { key: "Non Ascii Font", type: "string", value: "Monaco 12" }
    
    # Terminal behavior
    - { key: "ApplePressAndHoldEnabled", type: "int", value: 0 }
    - { key: "AppleScrollAnimationEnabled", type: "int", value: 0 }
    - { key: "AppleSmoothFixedFontsSizeThreshold", type: "int", value: 1 }
    - { key: "AppleAntiAliasingThreshold", type: "int", value: 1 }
    
    # Window and display settings
    - { key: "AppleWindowTabbingMode", type: "string", value: "manual" }
    - { key: "HapticFeedbackForEsc", type: "int", value: 0 }
    
    # Terminal settings
    - { key: "Character Encoding", type: "int", value: 4 }
    - { key: "Terminal Type", type: "string", value: "xterm-256color" }
    - { key: "Mouse Reporting", type: "int", value: 1 }
    - { key: "ASCII Anti Aliased", type: "int", value: 1 }
    - { key: "Non-ASCII Anti Aliased", type: "int", value: 1 }
    - { key: "Use Bold Font", type: "int", value: 1 }
    - { key: "Use Bright Bold", type: "int", value: 1 }
    - { key: "Use Italic Font", type: "int", value: 1 }
    - { key: "Draw Powerline Glyphs", type: "int", value: 1 }
    
    # Scrollback
    - { key: "Scrollback Lines", type: "int", value: 1000 }
    - { key: "Unlimited Scrollback", type: "int", value: 0 }

- name: Set up nnn configuration
  block:
    - name: Create nnn config directory
      file:
        path: "{{ user_home }}/.config/nnn"
        state: directory

    - name: Create nnn subdirectories
      file:
        path: "{{ user_home }}/.config/nnn/{{ item }}"
        state: directory
      loop:
        - bookmarks
        - mounts
        - plugins
        - sessions

    - name: Set nnn environment variables in zshrc
      blockinfile:
        path: "{{ user_home }}/.zshrc"
        marker: "# {mark} ANSIBLE MANAGED NNN CONFIG"
        block: |
          # nnn file manager configuration
          export NNN_PLUG='d:diffs;o:fzopen;p:mocq;z:autojump'
          export NNN_FIFO='/tmp/nnn.fifo'
          export NNN_COLORS='2136'
          export NNN_FCOLORS='c1e2272e006033f7c6d6abc4'

- name: Configure Ghostty terminal
  block:
    - name: Create Ghostty config directory
      file:
        path: "{{ user_home }}/.config/ghostty"
        state: directory

    - name: Create Ghostty configuration file
      copy:
        dest: "{{ user_home }}/.config/ghostty/config"
        content: |
          # Font configuration
          font-family = "MesloLGS Nerd Font"
          font-size = 13
          
          # Theme and appearance (matching iTerm2)
          background = fafafa
          foreground = 101010
          cursor-color = 000000
          cursor-text-color = ffffff
          selection-background = b3d6ff
          selection-foreground = 000000
          
          # ANSI colors (matching iTerm2 palette)
          palette = 0=141414  # Black
          palette = 1=b53c3c  # Red  
          palette = 2=00c200  # Green
          palette = 3=c7c700  # Yellow
          palette = 4=2743c8  # Blue
          palette = 5=c040be  # Magenta
          palette = 6=00c5c7  # Cyan
          palette = 7=c7c7c7  # White
          palette = 8=686868  # Bright Black
          palette = 9=dd797b  # Bright Red
          palette = 10=58e758 # Bright Green  
          palette = 11=ecec00 # Bright Yellow
          palette = 12=a7dcff # Bright Blue
          palette = 13=e17ee1 # Bright Magenta
          palette = 14=60ffff # Bright Cyan
          palette = 15=ffffff # Bright White
          
          # Terminal behavior
          scrollback-limit = 10000
          mouse-hide-while-typing = true
          confirm-close-surface = false
          
          # Performance
          macos-non-native-fullscreen = false
          
          # Key bindings (similar to iTerm2)
          keybind = cmd+t=new_tab
          keybind = cmd+w=close_surface
          keybind = cmd+shift+left=previous_tab
          keybind = cmd+shift+right=next_tab
          keybind = cmd+plus=increase_font_size:1
          keybind = cmd+minus=decrease_font_size:1
          keybind = cmd+zero=reset_font_size

- name: Restart terminals to apply font changes
  shell: |
    pkill -f iTerm2 || true
    pkill -f ghostty || true
  ignore_errors: yes